version: '3'

services:
  postgres:
    image: 'postgres:10-alpine'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vilki
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  main:
    build: .
    command: bash -c "npm run migrate && npm run start"
    links:
      - postgres:postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  postgres: